apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-test
  labels:
    key: value
spec:
  replicas: 1
  selector:
    key: value
  template:
    metadata:
      labels: 
       key: value
    spec:
      containers:
      - name: nginx-test
        image: nginx
