apiVersion: kubeadm.k8s.io/v1alpha3
imageRepository: registry.aliyuncs.com/google_containers
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
networking:
  dnsDomain: cluster.local
  podSubnet: "192.168.0.0/16"
